namespace: bookinfo1

details:
  port: 9080
  replicaCount: 1
  image: docker.io/istio/examples-bookinfo-details-v1:1.20.2

ratings:
  port: 9080
  replicaCount: 1
  image: docker.io/istio/examples-bookinfo-ratings-v1:1.20.2

reviews:
  port: 9080
  replicaCount: 3
  image: docker.io/istio/examples-bookinfo-reviews-v1:1.20.2

productpage:
  port: 9080
  replicaCount: 1
  image: docker.io/istio/examples-bookinfo-productpage-v1:1.20.2

