apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: {{ .Values.reviews.v1Weight }}
    - destination:
        host: reviews
        subset: v2
      weight: {{ .Values.reviews.v2Weight }}

