apiVersion: v2
name: bookinfo
description: A Helm chart for deploying the Istio Bookinfo application on Kubernetes

type: application

version: 0.1.0  # Increment this with each Helm chart update
appVersion: "1.16.0"  # Adjust this to match your Bookinfo app version

icon: "https://istio.io/latest/img/istio-logo.svg"

keywords:
  - istio
  - bookinfo
  - kubernetes
  - helm

maintainers:
  - name: Your Name
    email: your.email@example.com

sources:
  - https://istio.io/

dependencies: []  # You can define dependencies here if needed (like Kiali, Prometheus)

