{
 "title": "Custom-service-mesh-dashboard",
 "description": "created by kiran",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "2XX ",
   "type": "stat",
   "description": "successful requests",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"bookinfo1\", response_code=~\"2..\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3XX",
   "type": "stat",
   "description": "redirected requests",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"bookinfo1\", response_code=~\"3..\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4XX Errors",
   "type": "stat",
   "description": "4XX errors for bookinfo application",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"bookinfo1\", response_code=~\"4..\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5XX Errors",
   "type": "stat",
   "description": "5XX Errors for bookinfo application",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"bookinfo1\", response_code=~\"5..\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "total requests of bookinfo application",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"bookinfo1\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU-Usage (istiod)",
   "type": "timeseries",
   "description": "Istiod-cpu-usage",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "\r\nrate(container_cpu_usage_seconds_total{namespace=\"istio-system\", container=\"discovery\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Istiod)",
   "type": "gauge",
   "description": "Istiod-Memory-usage",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"istio-system\", container=\"discovery\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar CPU Usage",
   "type": "timeseries",
   "description": "Sidecar Cpu Usage in cores",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"bookinfo1\", container=\"istio-proxy\"}[5m])) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar Memory Usage",
   "type": "gauge",
   "description": "Sidecar Memory Usage in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"bookinfo1\", container=\"istio-proxy\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Gateway CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"istio-system\", container=\"istio-proxy\", pod=~\"istio-ingressgateway.*\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Gateway Memory Usage",
   "type": "gauge",
   "description": "Ingress Gateway Memory Usage in bytes",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"istio-system\", container=\"istio-proxy\", pod=~\"istio-ingressgateway.*\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}