apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.traffic.productpage.name }}
spec:
  hosts:
    - productpage
  http:
    - route:
        - destination:
            host: productpage
            subset: v1
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.traffic.reviews.name }}
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.traffic.ratings.name }}
spec:
  hosts:
    - ratings
  http:
    - route:
        - destination:
            host: ratings
            subset: v1
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.traffic.details.name }}
spec:
  hosts:
    - details
  http:
    - route:
        - destination:
            host: details
            subset: v1

