services:
  details:
    name: details
    app: details
    service: details
    port: 9080
    replicas: 1
    serviceAccount: bookinfo-details
    image:
      v1: docker.io/istio/examples-bookinfo-details-v1:1.20.3
  ratings:
    name: ratings
    app: ratings
    service: ratings
    port: 9080
    replicas: 1
    serviceAccount: bookinfo-ratings
    image:
      v1: docker.io/istio/examples-bookinfo-ratings-v1:1.20.3
  reviews:
    name: reviews
    app: reviews
    service: reviews
    port: 9080
    replicas: 1
    serviceAccount: bookinfo-reviews
    image:
      v1: docker.io/istio/examples-bookinfo-reviews-v1:1.20.3
      v2: docker.io/istio/examples-bookinfo-reviews-v2:1.20.3
      v3: docker.io/istio/examples-bookinfo-reviews-v3:1.20.3
  productpage:
    name: productpage
    app: productpage
    service: productpage
    port: 9080
    replicas: 1
    serviceAccount: bookinfo-productpage
    image:
      v1: docker.io/istio/examples-bookinfo-productpage-v1:1.20.3

# Gateway Configuration
gateway:
  name: bookinfo-gateway
  selector: ingressgateway
  port:
    number: 8080
    name: http
    protocol: HTTP
  hosts: "*"

# VirtualService Configuration
virtualservice:
  name: bookinfo
  hosts: "*"
  gateway: bookinfo-gateway
  port:
    number: 9080

# Destination Rules
destinationRules:
  productpage:
    name: productpage
    host: productpage
    subsets:
      - name: v1
        version: v1

  reviews:
    name: reviews
    host: reviews
    subsets:
      - name: v1
        version: v1
      - name: v2
        version: v2
      - name: v3
        version: v3

  ratings:
    name: ratings
    host: ratings
    subsets:
      - name: v1
        version: v1

  details:
    name: details
    host: details
    subsets:
      - name: v1
        version: v1

# Prometheus VirtualService
prometheus:
  virtualService:
    name: prometheus
    gateway: bookinfo-gateway
    destinationHost: prometheus.istio-system.svc.cluster.local
    port: 9090

# Kiali VirtualService
kiali:
  virtualService:
    name: kiali
    gateway: bookinfo-gateway
    uriPrefix: "/kiali"
    destinationHost: kiali.istio-system.svc.cluster.local
    port: 20001

# Grafana VirtualService
grafana:
  virtualService:
    name: grafana
    gateway: bookinfo-gateway
    uriPrefix: "/grafana"
    destinationHost: grafana.istio-system.svc.cluster.local
    port: 3000
ingress:
  enabled: true
service:
  type: LoadBalancer
  port: 9080
