apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: "{{ .Values.namespace }}"  # Ensure 'namespace' is defined in values.yaml
spec:
  selector:
    istio: ingressgateway  # This ensures that Istio's ingress gateway is used
  servers:
  - port:
      number: {{ .Values.gateway.port }}  # Define the port for the gateway in values.yaml
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.gateway.host }}"  # Define the host for the gateway in values.yaml
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookinfo
  namespace: "{{ .Values.namespace }}"  # Ensure 'namespace' is defined in values.yaml
spec:
  hosts:
  - "{{ .Values.virtualservice.host }}"  # Ensure 'host' is defined in values.yaml
  gateways:
  - bookinfo-gateway  # Ensure this matches the Gateway defined above
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage  # This should match the service name for productpage
        port:
          number: {{ .Values.virtualservice.productpagePort }}  # Ensure 'productpagePort' is defined in values.yaml

