{{- range $serviceName, $service := .Values.services }}
# Service
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    app: {{ $service.app }}
    service: {{ $service.service }}
spec:
  ports:
  - port: {{ $service.port }}
    name: http
  selector:
    app: {{ $service.app }}
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.serviceAccount | default (printf "bookinfo-%s" $service.name) }}
  labels:
    account: {{ $service.name }}
---
# Deployment - v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}-v1
  labels:
    app: {{ $service.app }}
    version: v1
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $service.app }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ $service.app }}
        version: v1
    spec:
      serviceAccountName: {{ $service.serviceAccount | default (printf "bookinfo-%s" $service.name) }}
      containers:
      - name: {{ $service.name }}
        image: {{ $service.image.v1 | default $service.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $service.port }}
---
{{- if eq $serviceName "reviews" }}
# Reviews v2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: {{ $service.image.v2 }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $service.port }}

---
# Reviews v3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  labels:
    app: reviews
    version: v3
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - name: reviews
        image: {{ $service.image.v3 }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $service.port }}
{{- end }}
{{- end }}

