apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: {{ .Values.gateway.selector }} # use istio default controller
  servers:
  - port:
      number: {{ .Values.gateway.port.number }}
      name: {{ .Values.gateway.port.name }}
      protocol: {{ .Values.gateway.port.protocol }}
    hosts:
    - "{{ .Values.gateway.hosts }}"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
spec:
  hosts:
  - "{{ .Values.virtualservice.hosts }}"
  gateways:
  - {{ .Values.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: {{ .Values.virtualservice.port.number }}

