apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Values.destinationRules.productpage.name }}
spec:
  host: {{ .Values.destinationRules.productpage.host }}
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Values.destinationRules.reviews.name }}
spec:
  host: {{ .Values.destinationRules.reviews.host }}
  subsets:
    {{- range .Values.destinationRules.reviews.subsets }}
    - name: {{ .name }}
      labels:
        version: {{ .version }}
    {{- end }}
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Values.destinationRules.ratings.name }}
spec:
  host: {{ .Values.destinationRules.ratings.host }}
  subsets:
    {{- range .Values.destinationRules.ratings.subsets }}
    - name: {{ .name }}
      labels:
        version: {{ .version }}
    {{- end }}
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Values.destinationRules.details.name }}
spec:
  host: {{ .Values.destinationRules.details.host }}
  subsets:
    {{- range .Values.destinationRules.details.subsets }}
    - name: {{ .name }}
      labels:
        version: {{ .version }}
    {{- end }}

