apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.grafana.virtualService.name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.grafana.virtualService.gateway }}
  http:
    - match:
        - uri:
            prefix: "{{ .Values.grafana.virtualService.uriPrefix }}"
      route:
        - destination:
            host: {{ .Values.grafana.virtualService.destinationHost }}
            port:
              number: {{ .Values.grafana.virtualService.port }}

