apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.prometheus.virtualService.name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.prometheus.virtualService.gateway }}
  http:
    - route:
        - destination:
            host: {{ .Values.prometheus.virtualService.destinationHost }}
            port:
              number: {{ .Values.prometheus.virtualService.port }}

